export const SET_ISLOGIN = 'SET_ISLOGIN'

export const SET_USERDATA = 'SET_USERDATA'

export const SET_NOTICE_COUNT = 'SET_NOTICE_COUNT'

export const SET_TASK_COUNT = 'SET_TASK_COUNT'

export const SET_OUTSOURCEDESC = 'SET_OUTSOURCEDESC'

export const SET_UPLOAD_FILE_LIST = 'SET_UPLOAD_FILE_LIST'

export const SET_FLOW_ARR_LIST_NUM = 'SET_FLOW_ARR_LIST_NUM'

export const SET_POST_LIST = 'SET_POST_LIST'

export const SET_STAFF_LIST = 'SET_STAFF_LIST'

export const SET_IS_UPLOAD = 'SET_IS_UPLOAD'
